# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.define "dmsbackend" do |dmsbackend|
        dmsbackend.vm.box = "ubuntu/trusty64"
        dmsbackend.vm.hostname = "dmsbackend"
        dmsbackend.vm.network "private_network", ip: "192.168.33.22"
        dmsbackend.vm.network "forwarded_port", guest: 8000, host: 8000
        dmsbackend.vm.synced_folder ".", "/home/vagrant/ansible"
        dmsbackend.vm.provision "shell", path: "setup.sh"
        dmsbackend.vm.provision "ansible" do |ansible|
            ansible.playbook = "dmsbackend.yml"
        end
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end

end