---
- hosts: backend-dms-app
  become: yes
  become_user: root
  environment:
    DATABASE_URL: postgresql://postgres:pass@localhost:5432/frontend-dms-app_development
    NODE_ENV: development

  tasks:
  - name: Install dependancies
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
    - npm
    - postgresql

  - name: Install nodejs
    shell: |
      curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      sudo apt-get install -y nodejs
    args:
      executable: /bin/bash

  -name: start postgresql 
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items:
    - postgresql

  # - name: Copy Postgres configurations
  #   template: src=templates/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
  #   notify:
  #     - Restart postgres

  - name: Create backend-dms-app folder
    file:
      path: backend-dms-app/
      state: directory
      mode: 0755
      owner: vagrant
      group: vagrant      

- name: Clone the backend-dms-app app from github
    git:
      repo: https://github.com/FlevianK/dms-backend.git
      dest: backend-dms-app/
      force: yes
    become: yes
    become_user: vagrant

- name: Run migrations and up the app
  shell: | 
    npm install
    createdb database_development
    npm run migrate
    nodemon app.js
  args:
    chdir: /home/vagrant/backend-dms-app/dms-backend     

