---
- hosts: frontend-dms-app
  become: yes
  become_user: root
  tasks:
  - name: Install dependancies
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
    - npm

  - name: Install nodejs
    shell: |
      curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      sudo apt-get install -y nodejs
    args:
      executable: /bin/bash

  - name: Create app folder
    file:
      path: frontend-app/
      state: directory
      mode: 0755
      owner: vagrant
      group: vagrant

  - name: Clone the frontend-dms-app app from github
    git:
      repo: https://github.com/FlevianK/cp2-document-management-system.git
      dest: frontend-app/
      force: yes
    become: yes
    become_user: vagrant

  - name: Install React dependancies and up the app
    shell: |
      npm install
      npm start
    args:
      chdir: /home/vagrant/frontend-app/cp2-document-management-system
