# -*- mode:ruby -*-
#vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

vagrant.configure("2") do |config|

  config.vm.define "frontent-dms-app" do |frontent-dms-app|
    frontent-dms-app.vm.box = "ubuntu/trusty64"
    frontent-dms-app.vm.hostname = "frontent-dms-app"
    frontent-dms-app.vm.network "private_network", ip: "192.168.33.20"
    frontent-dms-app.vm.network "forwarded_port", guest:80, host: 8080
    frontent-dms-app.vm.synced_folder ".", "/home/vagrant/ansible"
    frontent-dms-app.vm.provision "shell", path: "setup.sh"
    frontent-dms-app.vm.provision "ansible" do |ansible|
      ansible.playbook = "frontent-dms-app.yml"
    end
  end 

  config.vm.define "backend-dms-app" do |backend-dms-app|
    backend-dms-app.vm.box = "ubuntu/trusty64"
    backend-dms-app.vm.hostname = "backend-dms-app"
    backend-dms-app.vm.network "private_network", ip: "192.168.33.22"
    backend-dms-app.vm.network "forwarded_port", guest:80, host: 8000
    backend-dms-app.vm.synced_folder ".", "/home/vagrant/ansible"
    backend-dms-app.vm.provision "shell", path: "setup.sh"
    backend-dms-app.vm.provision "ansible" do |ansible|
      ansible.playbook = "backend-dms-app.yml"
    end
  end 

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

end